# Synced from flowx-ai/reusable-workflows-flowxai
version: 2
registries:
  flowx:
    type: python-index
    url: https://europe-python.pkg.dev/flowxai/python-dev/simple/
    username: _json_key
    password: ${{secrets.AI_SERVICES_SA_GAR_READONLY}}
updates:
  # Maintain dependencies
  # GH Actions are updated from flowx-ai/reusable-workflows-flowxai
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#insecure-external-code-execution
    insecure-external-code-execution: allow
    registries: "*"
    open-pull-requests-limit: 20
