export const defaultAgents: any[] = [
  { name: 'Assistant', code: 'Assistant' },
  { name: 'Analyst', code: 'Analyst' },
  { name: 'Designer', code: 'Designer' },
  { name: 'Developer', code: 'Developer' },
  { name: 'Auditor', code: 'Auditor' },
  { name: 'Inspector', code: 'Inspector' },
  { name: 'Supervisor', code: 'Supervisor' },
]

// All available evaluators from openevals + agentevals
export const defaultEvaluators: any[] = [
  // --- openevals LLM-as-judge ---
  {
    name: 'Correctness',
    code: 'correctness',
    category: 'llm_judge',
    library: 'openevals',
    image: 'text',
    tags: ['LLM Judge'],
    requiresInput: true,
    requiresReference: true,
    requiresLlm: true,
    details: 'Checks if the output is correct given a reference answer.',
  },
  {
    name: 'Conciseness',
    code: 'conciseness',
    category: 'llm_judge',
    library: 'openevals',
    image: 'text',
    tags: ['LLM Judge'],
    requiresInput: true,
    requiresReference: false,
    requiresLlm: true,
    details: 'Evaluates whether the output is concise and avoids unnecessary verbosity.',
  },
  {
    name: 'Hallucination',
    code: 'hallucination',
    category: 'llm_judge',
    library: 'openevals',
    image: 'text',
    tags: ['LLM Judge'],
    requiresInput: true,
    requiresReference: true,
    requiresLlm: true,
    details: 'Detects whether the output contains fabricated or unsupported claims.',
  },
  {
    name: 'Toxicity',
    code: 'toxicity',
    category: 'llm_judge',
    library: 'openevals',
    image: 'text',
    tags: ['LLM Judge'],
    requiresInput: true,
    requiresReference: false,
    requiresLlm: true,
    details: 'Checks if the output contains toxic, harmful, or offensive content.',
  },
  {
    name: 'Answer Relevance',
    code: 'answer_relevance',
    category: 'llm_judge',
    library: 'openevals',
    image: 'text',
    tags: ['LLM Judge', 'RAG'],
    requiresInput: true,
    requiresReference: false,
    requiresLlm: true,
    details: 'Evaluates whether the output is relevant to the input question.',
  },
  {
    name: 'PII Leakage',
    code: 'pii_leakage',
    category: 'llm_judge',
    library: 'openevals',
    image: 'text',
    tags: ['LLM Judge', 'Safety'],
    requiresInput: true,
    requiresReference: false,
    requiresLlm: true,
    details: 'Detects personally identifiable information (PII) leaked in the output.',
  },
  {
    name: 'Prompt Injection',
    code: 'prompt_injection',
    category: 'llm_judge',
    library: 'openevals',
    image: 'text',
    tags: ['LLM Judge', 'Safety'],
    requiresInput: true,
    requiresReference: false,
    requiresLlm: true,
    details: 'Detects whether the model fell victim to a prompt injection attack.',
  },
  {
    name: 'Jailbreak',
    code: 'jailbreak',
    category: 'llm_judge',
    library: 'openevals',
    image: 'text',
    tags: ['LLM Judge', 'Safety'],
    requiresInput: true,
    requiresReference: false,
    requiresLlm: true,
    details: 'Detects whether the model was successfully jailbroken to bypass safety guardrails.',
  },
  {
    name: 'RAG Helpfulness',
    code: 'rag_helpfulness',
    category: 'llm_judge',
    library: 'openevals',
    image: 'text',
    tags: ['LLM Judge', 'RAG'],
    requiresInput: true,
    requiresReference: false,
    requiresLlm: true,
    details: 'Evaluates whether a RAG response is helpful and complete.',
  },
  {
    name: 'RAG Groundedness',
    code: 'rag_groundedness',
    category: 'llm_judge',
    library: 'openevals',
    image: 'text',
    tags: ['LLM Judge', 'RAG'],
    requiresInput: true,
    requiresReference: false,
    requiresLlm: true,
    details: 'Checks if the RAG output is grounded in the retrieved context.',
  },
  {
    name: 'RAG Retrieval Relevance',
    code: 'rag_retrieval_relevance',
    category: 'llm_judge',
    library: 'openevals',
    image: 'text',
    tags: ['LLM Judge', 'RAG'],
    requiresInput: true,
    requiresReference: false,
    requiresLlm: true,
    details: 'Evaluates whether retrieved documents are relevant to the query.',
  },
  {
    name: 'Code Correctness',
    code: 'code_correctness',
    category: 'llm_judge',
    library: 'openevals',
    image: 'text',
    tags: ['LLM Judge', 'Code'],
    requiresInput: true,
    requiresReference: true,
    requiresLlm: true,
    details: 'Evaluates if generated code is correct given a reference solution.',
  },
  // --- openevals deterministic ---
  {
    name: 'Exact Match',
    code: 'exact_match',
    category: 'deterministic',
    library: 'openevals',
    image: 'text',
    tags: ['Deterministic'],
    requiresInput: false,
    requiresReference: true,
    requiresLlm: false,
    details: 'Checks if the output exactly matches the reference (deep JSON equality).',
  },
  {
    name: 'Levenshtein Distance',
    code: 'levenshtein_distance',
    category: 'deterministic',
    library: 'openevals',
    image: 'text',
    tags: ['Deterministic'],
    requiresInput: false,
    requiresReference: true,
    requiresLlm: false,
    details: 'Computes normalized edit distance between output and reference (0=different, 1=identical).',
  },
  {
    name: 'JSON Match',
    code: 'json_match',
    category: 'deterministic',
    library: 'openevals',
    image: 'json',
    tags: ['Deterministic', 'JSON'],
    requiresInput: false,
    requiresReference: true,
    requiresLlm: false,
    details: 'Structurally compares JSON output against reference JSON.',
  },
  // --- agentevals trajectory ---
  {
    name: 'Trajectory Strict Match',
    code: 'trajectory_match_strict',
    category: 'trajectory',
    library: 'agentevals',
    image: 'text',
    tags: ['Trajectory'],
    requiresInput: false,
    requiresReference: true,
    requiresLlm: false,
    details: 'Checks if agent tool calls match reference trajectory in exact order.',
  },
  {
    name: 'Trajectory Unordered Match',
    code: 'trajectory_match_unordered',
    category: 'trajectory',
    library: 'agentevals',
    image: 'text',
    tags: ['Trajectory'],
    requiresInput: false,
    requiresReference: true,
    requiresLlm: false,
    details: 'Checks if agent tool calls match reference regardless of order.',
  },
  {
    name: 'Trajectory Subset Match',
    code: 'trajectory_match_subset',
    category: 'trajectory',
    library: 'agentevals',
    image: 'text',
    tags: ['Trajectory'],
    requiresInput: false,
    requiresReference: true,
    requiresLlm: false,
    details: 'Checks if output trajectory contains at least the reference tool calls.',
  },
  {
    name: 'Trajectory Superset Match',
    code: 'trajectory_match_superset',
    category: 'trajectory',
    library: 'agentevals',
    image: 'text',
    tags: ['Trajectory'],
    requiresInput: false,
    requiresReference: true,
    requiresLlm: false,
    details: 'Checks if reference trajectory contains at least the output tool calls.',
  },
  {
    name: 'Trajectory LLM Judge',
    code: 'trajectory_llm_judge',
    category: 'trajectory',
    library: 'agentevals',
    image: 'text',
    tags: ['Trajectory', 'LLM Judge'],
    requiresInput: false,
    requiresReference: false,
    requiresLlm: true,
    details: 'Uses an LLM to evaluate the quality of an agent\'s trajectory.',
  },
]

export const defaultExpTypes: any[] = [
  {
    name: 'Dataset',
    code: 'Dataset',
    evaluators: defaultEvaluators.filter((e) => e.category !== 'trajectory'),
  },
  {
    name: 'Agent Trajectory',
    code: 'AgentTrajectory',
    evaluators: defaultEvaluators.filter((e) => e.category === 'trajectory'),
  },
  {
    name: 'Custom',
    code: 'Custom',
    evaluators: defaultEvaluators,
  },
]

export const defaultLLMProviders: any[] = [
  {
    name: 'Ollama',
    code: 'Ollama',
    models: [],
  },
  {
    name: 'OpenAI',
    code: 'OpenAI',
    models: [
      { name: 'GPT-4o', model: 'gpt-4o' },
      { name: 'GPT-4o Mini', model: 'gpt-4o-mini' },
      { name: 'o1', model: 'o1' },
      { name: 'o1 Mini', model: 'o1-mini' },
      { name: 'GPT-4 Turbo', model: 'gpt-4-turbo' },
    ],
  },
  {
    name: 'Google',
    code: 'Google',
    models: [
      { name: 'Gemini 2.0 Flash', model: 'gemini-2.0-flash' },
      { name: 'Gemini 1.5 Pro', model: 'gemini-1.5-pro' },
      { name: 'Gemini 1.5 Flash', model: 'gemini-1.5-flash' },
    ],
  },
  {
    name: 'Anthropic',
    code: 'Anthropic',
    models: [
      { name: 'Claude Opus 4.6', model: 'claude-opus-4-6' },
      { name: 'Claude Sonnet 4.5', model: 'claude-sonnet-4-5-20250929' },
      { name: 'Claude Haiku 4.5', model: 'claude-haiku-4-5-20251001' },
    ],
  },
  {
    name: 'Any',
    code: 'Any',
    models: [{ name: 'Any', model: 'any' }],
  },
]
