name: build

on:
  workflow_call:
    inputs:
      app_version:
        description: 'Application version'
        required: true
        type: string
      hc_version:
        description: 'Health check version'
        required: true
        type: string
      build_args:
        description: 'Container build args'
        required: false
        type: string
      repo_name:
        description: 'Repo name'
        required: true
        type: string
      artifact_registry:
        description: 'Image Registry'
        required: true
        type: string
      artifact_registry_images:
        description: 'Image Registry Project'
        required: true
        type: string
      gcp_workload_identity_provider:
        description: "GCP Workload Identity Provider"
        required: true
        type: string
      gcp_service_account:
        description: "GCP Service Account"
        required: true
        type: string
      cache-to:
        description: "Where to send cache"
        required: true
        type: string
      cache-from:
        description: "From where to fetch cache"
        required: true
        type: string
      images:
        description: "Where to push"
        required: true
        type: string
    outputs:
      image_tag:
        description: "Image tag"
        value: ${{ jobs.build.outputs.image_tag }}
      image_digest:
        description: "Image digest"
        value: ${{ jobs.build.outputs.image_digest }}


jobs:
  build:
    name: app
    runs-on: ubuntu-24.04
    outputs:
      image_tag: ${{ fromJSON(steps.meta.outputs.json).tags[0] }}
      image_digest: ${{ steps.build.outputs.digest }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

      - name: Free Disk Space (Ubuntu)
        env:
          cleanup_space: ${{ vars.CLEANUP_SPACE }}
        if: ${{ env.cleanup_space == 'true' }}
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be #v1.3.1
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false

          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Configure healthcheck version
        if: ${{ hashFiles('healthcheck.json') != '' }}
        run: |
          sed -i -e "s/VERSION/${{ inputs.hc_version }}/g" healthcheck.json

      - id: auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@71f986410dfbc7added4569d411d040a91dc6935 #v2.1.8
        with:
          token_format: access_token
          workload_identity_provider: ${{ inputs.gcp_workload_identity_provider }}
          service_account: ${{ inputs.gcp_service_account }}
          access_token_lifetime: 4600s
          create_credentials_file: true
          cleanup_credentials: true

      - name: Login to Harbor Registry
        if: >-
          github.ref == 'refs/heads/main' ||
          github.ref == 'refs/heads/master' ||
          startsWith(github.ref, 'refs/heads/release/')
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 #v3.3.0
        with:
          registry: harbor-jx.dev.rd.flowx.ai/flowx-dev-v2
          username: ${{ vars.HARBOR_USERNAME}}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Login to Artifact Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 #v3.3.0
        with:
          registry: europe-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 #v5.7.0
        with:
          images: |
            ${{ inputs.images }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=${{ inputs.hc_version }}
            type=ref,event=branch,enable={{is_default_branch}}
            type=ref,event=branch,enable=${{ !startsWith(github.ref, 'refs/heads/release/') }}
            type=ref,event=pr,prefix=${{ inputs.app_version }}-pr,suffix=-${{github.run_number}}-${{ inputs.short_sha }}
            type=ref,event=pr,prefix=pr

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 #v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 #v3.10.0

      - name: Build and push
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 #v6.15.0
        id: build
        env:
          DOCKER_BUILD_SUMMARY: false
        with:
          context: .
          platforms: linux/amd64
          push: true
          build-args: |
            ${{ inputs.build_args }}
          tags: |
            ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: |
            ${{ inputs.cache-from}}
          cache-to: |
            ${{ inputs.cache-to }}
          secret-files: |
            "gar=${{ steps.auth.outputs.credentials_file_path }}"
