name: Supply Chain Security

on:
  workflow_call:
    inputs:
      app_version:
        description: 'Application version'
        required: true
        type: string
      image_tag:
        description: 'Build image tag'
        required: true
        type: string
      image_digest:
        description: 'Build image digest'
        required: true
        type: string
      artifact_registry:
        description: 'Image Registry'
        required: true
        type: string
      artifact_registry_images:
        description: 'Image Registry Project'
        required: true
        type: string
      repo_name:
        description: 'Repo name'
        required: true
        type: string
      gcp_workload_identity_provider:
        description: "GCP Workload Identity Provider"
        required: true
        type: string
      gcp_service_account:
        description: "GCP Service Account"
        required: true
        type: string
      cosign_tlog_upload:
        description: 'Decide if we want to upload to Rekor'
        required: false
        type: string
        default: 'false'
      cosign_ignore_tlog:
        description: 'Ignore missing Rekor record'
        required: false
        type: string
        default: 'true'

jobs:
  supply-chain:
    runs-on: ubuntu-24.04
    outputs:
      hashes: ${{ steps.sbom-hash.outputs.hashes}}
    steps:
      #checkout is not actually needed, the apps can use the credentials but the auth action throws a warning
      #Messsage: The "create_credentials_file" option is true, but the current GitHub workspace is empty.
      #https://github.com/google-github-actions/auth?tab=readme-ov-file#inputs-miscellaneous
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

      - id: auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@71f986410dfbc7added4569d411d040a91dc6935 #v2.1.8
        with:
          token_format: access_token
          workload_identity_provider: ${{ inputs.gcp_workload_identity_provider }}
          service_account: ${{ inputs.gcp_service_account }}
          access_token_lifetime: 600s
          create_credentials_file: true
          cleanup_credentials: true

      - name: Login to Artifact Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 #v3.3.0
        with:
          registry: europe-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Set Repo Digest
        env:
          IMAGE_TAG: ${{ inputs.image_tag }}
        id: digest
        run: |
          repo_digest=${{ inputs.artifact_registry}}/${{ inputs.artifact_registry_images }}/${{ inputs.repo_name }}:${{ inputs.app_version }}@${{ inputs.image_digest}}
          echo "RepoDigest: ${repo_digest}"
          echo "repo_digest=${repo_digest}" >> $GITHUB_OUTPUT

      - name: Generate SBOM artifact
        uses: aquasecurity/trivy-action@18f2510ee396bbf400402947b394f2dd8c87dbb0 #0.29.0
        env:
          TRIVY_DB_REPOSITORY: europe-docker.pkg.dev/flowxai/remote/aquasecurity/trivy-db,ghcr.io/aquasecurity/trivy-db,public.ecr.aws/aquasecurity/trivy-db,docker.io/aquasec/trivy-db
          TRIVY_JAVA_DB_REPOSITORY: europe-docker.pkg.dev/flowxai/remote/aquasecurity/trivy-java-db,ghcr.io/aquasecurity/trivy-java-db,public.ecr.aws/aquasecurity/trivy-java-db,docker.io/aquasec/trivy-java-db
          TRIVY_DEBUG: true
        with:
          image-ref: ${{ steps.digest.outputs.repo_digest }}
          format: 'cyclonedx'
          scanners: 'vuln'
          output: "sbom.cyclonedx"
          cache-dir: .trivy
          cache: 'true'
          timeout: '30m'

      - name: Generate HTML report
        uses: aquasecurity/trivy-action@18f2510ee396bbf400402947b394f2dd8c87dbb0 #0.29.0
        with:
          image-ref: ${{ steps.digest.outputs.repo_digest }}
          #image-ref: '${{ needs.init.outputs.artifact_registry }}/dev/${{ needs.init.outputs.repo_name }}:${{ steps.tag.outputs.number }}'
          #format: 'table'
          format: 'template'
          template: "@$HOME/.local/bin/trivy-bin/contrib/html.tpl"
          output: vuln-scan-${{ inputs.app_version }}.html
          exit-code: '0'
          ignore-unfixed: false
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      # Write Results to Job Summary
      - name: Add Scan Results to Job Summary
        if: github.event_name == 'pull_request'
        run: |
          # Remove <head>  block
          sed -i '/<head>/,/<\/head>/d' vuln-scan-${{ inputs.app_version }}.html

          cat vuln-scan-${{ inputs.app_version }}.html >> $GITHUB_STEP_SUMMARY

      - name: Generate SBOM hash
        shell: bash
        id: sbom-hash
        run: |
          # sha256sum generates sha256 hash for sbom.
          # base64 -w0 encodes to base64 and outputs on a single line.
          # sha256sum /tmp/sbom.tar.gz ... | base64 -w0
          echo "hashes=$(sha256sum sbom.cyclonedx | base64 -w0)" >> "$GITHUB_OUTPUT"

      - name: Upload SBOM to GitHub
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 #v4.4.3
        with:
          name: "sbom.cyclonedx"
          path: "sbom.cyclonedx"
          retention-days: 5

      - name: Upload scan to GitHub
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 #v4.4.3
        with:
          name: "vuln-scan-${{ inputs.app_version }}.html"
          path: "vuln-scan-${{ inputs.app_version }}.html"
          retention-days: 5

      - name: dep-track
        if: ${{ vars.DEP_TRACK_UPLOAD == 'true' }}
        uses: DependencyTrack/gh-upload-sbom@48feab3080ff9e8f51f4d21861d9fc914eb744f5 #v3.1.0
        with:
          serverhostname: '${{ vars.DEPENDENCYTRACK_HOSTNAME}}'
          apikey: ${{ secrets.DEPENDENCYTRACK_APIKEY }}
          projectname: '${{ inputs.repo_name }}'
          projectversion: '${{ inputs.app_version }}'
          bomfilename: "sbom.cyclonedx"
          autocreate: true

      - name: Upload SBOM to registry
        run: |
          gcloud artifacts sbom load --source="sbom.cyclonedx" --uri=${{ inputs.image_tag }}

      - name: Install cosign
        uses: sigstore/cosign-installer@d7d6bc7722e3daa8354c50bcb52f4837da5e9b6a #3.8.1

      - name: Keyless signing of image
        run: |
          echo cosign sign --recursive --yes ${{ steps.digest.outputs.repo_digest }} --tlog-upload=${{ inputs.cosign_tlog_upload }}

      - name: Verify the image
        if: >-
          github.ref == 'refs/heads/main' ||
          github.ref == 'refs/heads/master' ||
          startsWith(github.ref, 'refs/heads/release/')
        run: |
          echo cosign verify --insecure-ignore-tlog=${{ inputs.cosign_ignore_tlog }} ${{ steps.digest.outputs.repo_digest }} \
            --certificate-identity-regexp "https://github.com/${{ github.repository }}/.github/workflows/_supply-chain.yml@refs/heads/main" \
            --certificate-oidc-issuer "https://token.actions.githubusercontent.com"
          # | jq .

      - name: Run Trivy in GitHub SBOM mode and submit results to Dependency Graph
        if: >-
          github.ref == 'refs/heads/main' ||
          github.ref == 'refs/heads/master' ||
          startsWith(github.ref, 'refs/heads/release/')
        uses: aquasecurity/trivy-action@18f2510ee396bbf400402947b394f2dd8c87dbb0 #0.29.0
        env:
          TRIVY_DB_REPOSITORY: europe-docker.pkg.dev/flowxai/remote/aquasecurity/trivy-db:2
          TRIVY_JAVA_DB_REPOSITORY: europe-docker.pkg.dev/flowxai/remote/aquasecurity/trivy-java-db:1
          TRIVY_DEBUG: true
        with:
          scan-type: 'fs'
          format: 'github'
          output: 'dependency-results.sbom.json'
          image-ref: '.'
          github-pat: ${{ secrets.GITHUB_TOKEN }}
          cache-dir: .trivy
          cache: 'true'

  image-provenance:
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v2.1.0
    if: >-
      github.ref == 'refs/heads/main' ||
      github.ref == 'refs/heads/master' ||
      startsWith(github.ref, 'refs/heads/release/')
    with:
      image: ${{ inputs.artifact_registry}}/${{ inputs.artifact_registry_images }}/${{ inputs.repo_name }}
      digest: ${{ inputs.image_digest}}
      gcp-workload-identity-provider: ${{ inputs.gcp_workload_identity_provider }}
      gcp-service-account: ${{ inputs.gcp_service_account }}
      private-repository: true

  sbom-provenance:
    needs: [supply-chain]
    if: >-
      github.ref == 'refs/heads/main' ||
      github.ref == 'refs/heads/master' ||
      startsWith(github.ref, 'refs/heads/release/')
    # Must be refernced by a tag. https://github.com/slsa-framework/slsa-github-generator/blob/main/internal/builders/container/README.md#referencing-the-slsa-generator
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v2.1.0
    with:
      base64-subjects: "${{ needs.supply-chain.outputs.hashes }}"
      provenance-name: "sbom.intoto.jsonl"
      upload-assets: false
      private-repository: true
