name: ci

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: read
  pull-requests: write
  id-token: write
  checks: read
  repository-projects: read
  statuses: read

jobs:
  init:
    uses: ./.github/workflows/_compute-vars.yml

  build:
    needs: [init]
    permissions:
      contents: 'write'
      id-token: 'write'
    uses: ./.github/workflows/_build.yml
    with:
      app_version: ${{ needs.init.outputs.app_version }}
      hc_version: ${{ needs.init.outputs.hc_version }}
      repo_name: ${{ needs.init.outputs.repo_name }}
      artifact_registry: ${{ needs.init.outputs.artifact_registry }}
      artifact_registry_images: 'ai-docker-dev'
      gcp_workload_identity_provider: ${{ needs.init.outputs.gcp_workload_identity_provider }}
      gcp_service_account: ${{ needs.init.outputs.gcp_service_account }}
      images: |
        ${{ needs.init.outputs.artifact_registry }}/ai-docker-dev/${{ needs.init.outputs.repo_name }}
      cache-from: |
        type=registry,ref=${{ needs.init.outputs.artifact_registry }}/ai-buildcache/${{ needs.init.outputs.repo_name }}:buildcache-main
        type=registry,ref=${{ needs.init.outputs.artifact_registry }}/ai-buildcache/${{ needs.init.outputs.repo_name }}:buildcache-pr${{ github.event.number }}
      cache-to: |
        type=registry,ref=${{ needs.init.outputs.artifact_registry }}/ai-buildcache/${{ needs.init.outputs.repo_name }}:buildcache-pr${{ github.event.number }},mode=max
      build_args: |
        APP_NAME=${{ needs.init.outputs.app_name }}
        VERSION=${{ needs.init.outputs.app_version }}
        PACKAGES=${{ vars.PACKAGES}}
        PURGE=${{ vars.PURGE}}
    secrets: inherit

  publish:
    permissions:
      contents: 'write'
      id-token: 'write'
      pull-requests: read
    needs: [init,build]
    uses: ./.github/workflows/_publish-chart.yml
    with:
      app_version: ${{ needs.init.outputs.hc_version }}
      repo_name: ${{ needs.init.outputs.repo_name }}
      artifact_registry: ${{ needs.init.outputs.artifact_registry }}
      artifact_registry_images: 'ai-docker-dev'
      artifact_registry_charts: 'ai-charts-dev'
      harbor_chart_registry: ${{ needs.init.outputs.harbor_chart_registry }}
      harbor_chart_project: 'flowx-dev-v2-snapshots'
      gcp_workload_identity_provider: ${{ needs.init.outputs.gcp_workload_identity_provider }}
      gcp_service_account: ${{ needs.init.outputs.gcp_service_account }}
    secrets: inherit

  security:
    needs: [init,build]
    permissions:
      actions: 'read' # for detecting the Github Actions environment.
      contents: 'write' # Needed for release uploads
      id-token: 'write' # for creating OIDC tokens for signing.
      packages: 'write' # for uploading attestations.
    uses: ./.github/workflows/_supply-chain.yml
    with:
      repo_name: ${{ needs.init.outputs.repo_name }}
      app_version: ${{ needs.init.outputs.app_version }}-pr${{ github.event.number }}
      image_tag: ${{ needs.build.outputs.image_tag }}
      image_digest: ${{ needs.build.outputs.image_digest }}
      artifact_registry: ${{ needs.init.outputs.artifact_registry }}
      artifact_registry_images: 'ai-docker-dev'
      gcp_workload_identity_provider: ${{ needs.init.outputs.gcp_workload_identity_provider }}
      gcp_service_account: ${{ needs.init.outputs.gcp_service_account }}
    secrets: inherit

  check-label:
    needs: [publish]
    outputs:
      labels: ${{ steps.label.outputs.labels }}
    runs-on: ubuntu-24.04
    steps:
    - name: get cicd labels
      id: label
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        labels=$(gh api --jq '.labels.[] | select(.name | contains("cicd-")).name' /repos/${{ github.repository}}/pulls/${{ github.event.number }} | sed 's/.*/"&"/g' | awk '{printf "%s%s", sep, $0; sep=", "}')
        echo "labels=[${labels}]" | tee -a $GITHUB_OUTPUT $GITHUB_ENV

  devenv-configure:
    needs: [init, check-label]
    if: ${{ toJson(fromJson(needs.check-label.outputs.labels)) != '[]' }}
    strategy:
      max-parallel: 1 #Because of conflict when committing to env repo
      #matrix: ${{ fromJson(needs.devenv-matrix.outputs.matrix )}}
      matrix:
        label: ${{ fromJson(needs.check-label.outputs.labels )}}
    uses: ./.github/workflows/_devenv.yml
    with:
      app_version: ${{ needs.init.outputs.hc_version }}
      app_name: ${{ needs.init.outputs.repo_name }}
      label: ${{ matrix.label }}
    secrets: inherit

  devenv-pipeline-start:
    needs: [check-label, init, devenv-configure]
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        label: ${{ fromJson(needs.check-label.outputs.labels )}}
    steps:
    - name: Get env from label
      id: vars
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        # extract env repo name, branch name and devenv pr from labels

        # devenv/academyenv/demoenv
        env_type=$(echo ${{ matrix.label }} | tr '[:upper:]' '[:lower:]' | awk -F"/" '{print $1}' | awk -F"-" '{print $2}')

        # dev-environments
        env_repo_name="${env_type%env}-environments"
        echo "env_repo_name=${env_repo_name}" | tee -a $GITHUB_OUTPUT $GITHUB_ENV


        # versioning-with-timer-events
        env_branch=$(echo ${{ matrix.label }} | tr '[:upper:]' '[:lower:]' | awk -F"/" '{print $2}')
        echo "env_branch=${env_branch}"  | tee -a $GITHUB_OUTPUT $GITHUB_ENV

    - name: Get Token
      id: get_workflow_token
      uses: peter-murray/workflow-application-token-action@d17e3a9a36850ea89f35db16c1067dd2b68ee343 #4.0.1
      with:
        application_id: ${{ vars.APPLICATION_ID }}
        application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
        revoke_token: true

    - name: Check out environment repo
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7
      with:
        token: ${{ steps.get_workflow_token.outputs.token }}
        repository: flowx-ai/${{ steps.vars.outputs.env_repo_name }}
        path: ${{ steps.vars.outputs.env_repo_name }}
        ref: ${{ steps.vars.outputs.env_branch }}

    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: devenv-${{ steps.vars.outputs.env_branch }}
        path: ${{ steps.vars.outputs.env_repo_name }}

    # Create a multiline string to be used by the git-auto-commit Action
    - name: Set commit message
      id: commit_message_step
      working-directory:  ${{ steps.vars.outputs.env_repo_name }}
      run: |
        echo 'commit_message<<EOF' >> $GITHUB_OUTPUT
        cat commitmessage.txt >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT
        rm -f commitmessage.txt


    - name: Commit changes
      id: commit_values
      uses: stefanzweifel/git-auto-commit-action@e348103e9026cc0eee72ae06630dbe30c8bf7a79 #v5.1.0
      with:
        #commit_message: "Deploying snapshot for `${{ needs.build.outputs.affected_apps}}` with version ${{ needs.init.outputs.app_version }}-pr${{ github.event.number }}-${{ github.sha }}}"
        commit_message: ${{ steps.commit_message_step.outputs.commit_message }}
        repository: ${{ steps.vars.outputs.env_repo_name }}
        branch: ${{ steps.vars.outputs.env_branch }}
        #commit_options: "--allow-empty"
        #skip_dirty_check: true
