name: Release

on:
  push:
    branches:
      - main
      - master
      - release/*.x


jobs:
  init:
    uses: ./.github/workflows/_compute-vars.yml

  build:
    needs: [init]
    permissions:
      contents: 'write'
      id-token: 'write'
    uses: ./.github/workflows/_build.yml
    with:
      app_version: ${{ needs.init.outputs.app_version }}
      hc_version: ${{ needs.init.outputs.hc_version }}
      repo_name: ${{ needs.init.outputs.repo_name }}
      artifact_registry: ${{ needs.init.outputs.artifact_registry }}
      artifact_registry_images: 'ai-docker-release'
      gcp_workload_identity_provider: ${{ needs.init.outputs.gcp_workload_identity_provider }}
      gcp_service_account: ${{ needs.init.outputs.gcp_service_account }}
      images: |
        ${{ needs.init.outputs.artifact_registry }}/ai-docker-release/${{ needs.init.outputs.repo_name }}
        harbor-jx.dev.rd.flowx.ai/flowx-dev-v2/${{ needs.init.outputs.repo_name }}
      cache-from: |
        type=registry,ref=${{ needs.init.outputs.artifact_registry }}/ai-buildcache/${{ needs.init.outputs.repo_name }}:buildcache-main
      cache-to: |
        type=registry,ref=${{ needs.init.outputs.artifact_registry }}/ai-buildcache/${{ needs.init.outputs.repo_name }}:buildcache-main,mode=max
      build_args: |
        APP_NAME=${{ needs.init.outputs.app_name }}
        VERSION=${{ needs.init.outputs.app_version }}
        PACKAGES=${{ vars.PACKAGES}}
        PURGE=${{ vars.PURGE}}
    secrets: inherit

  publish:
    permissions:
      contents: 'write'
      id-token: 'write'
    needs: [init,build]
    uses: ./.github/workflows/_publish-chart.yml
    with:
      app_version: ${{ needs.init.outputs.hc_version }}
      repo_name: ${{ needs.init.outputs.repo_name }}
      artifact_registry: ${{ needs.init.outputs.artifact_registry }}
      artifact_registry_images: 'ai-docker-release'
      artifact_registry_charts: 'ai-charts-release'
      harbor_chart_registry: ${{ needs.init.outputs.harbor_chart_registry }}
      harbor_chart_project: 'flowx-dev-v2'
      gcp_workload_identity_provider: ${{ needs.init.outputs.gcp_workload_identity_provider }}
      gcp_service_account: ${{ needs.init.outputs.gcp_service_account }}
      commit_helm_values: 'true'
    secrets: inherit

  security:
    needs: [init,build]
    permissions:
      actions: 'read' # for detecting the Github Actions environment.
      contents: 'write' # Needed for release uploads
      id-token: 'write' # for creating OIDC tokens for signing.
      packages: 'write' # for uploading attestations.
    uses: ./.github/workflows/_supply-chain.yml
    with:
      repo_name: ${{ needs.init.outputs.repo_name }}
      app_version: ${{ needs.init.outputs.app_version }}
      image_tag: ${{ needs.build.outputs.image_tag }}
      image_digest: ${{ needs.build.outputs.image_digest }}
      artifact_registry: ${{ needs.init.outputs.artifact_registry }}
      artifact_registry_images: 'ai-docker-release'
      gcp_workload_identity_provider: ${{ needs.init.outputs.gcp_workload_identity_provider }}
      gcp_service_account: ${{ needs.init.outputs.gcp_service_account }}
    secrets: inherit

  gh-release:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    needs: [init, build, security, publish]
    steps:
    - uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e #4.1.7
      with:
        name: "sbom.cyclonedx"

    - uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e #v4.1.7
      with:
        name: "sbom.intoto.jsonl"

    - uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e #v4.1.7
      with:
        name: "vuln-scan-${{ needs.init.outputs.app_version }}.html"

    - name: Get Token
      id: get_workflow_token
      uses: peter-murray/workflow-application-token-action@d17e3a9a36850ea89f35db16c1067dd2b68ee343 #4.0.1
      with:
        application_id: ${{ vars.APPLICATION_ID }}
        application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
        revoke_token: true

    - name: Create Release
      uses: ncipollo/release-action@440c8c1cb0ed28b9f43e4d1d670870f059653174 #v1.16.0
      with:
        allowUpdates: false
        draft: false
        makeLatest: ${{ needs.init.outputs.make_latest }}
        name: ${{ needs.init.outputs.app_version }}
        tag: v${{ needs.init.outputs.app_version }}
        generateReleaseNotes: true
        token: ${{ steps.get_workflow_token.outputs.token }}
        commit: ${{ needs.publish.outputs.commit_hash }}
        artifacts: "sbom.cyclonedx,sbom.intoto.jsonl, vuln-scan-${{ needs.init.outputs.app_version }}.html"
