name: Trigger Renovate

on:
  workflow_run:
    workflows: [Release]
    types:
    - completed

jobs:
  trigger-renovate:
    name: Trigger Renovate
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Get Token
      id: get_workflow_token
      uses: peter-murray/workflow-application-token-action@d17e3a9a36850ea89f35db16c1067dd2b68ee343 #4.0.1
      with:
        application_id: ${{ vars.APPLICATION_ID }}
        application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
        revoke_token: true

    - name: Trigger workflow on other repo
      uses: actions/github-script@v7
      with:
        github-token: ${{ steps.get_workflow_token.outputs.token }}
        script: |
          github.rest.actions.createWorkflowDispatch({
            owner: '${{ github.repository_owner }}',
            repo: 'reusable-workflows-flowxai',
            workflow_id: 'renovate.yml',
            ref: 'main'
          })
